#include "starspeed/splashs.hpp"
namespace StarSpeed {
    std::vector<std::string> SPLASHES = {
        "Here could be COLOR{\"color\":[144,0,0,255],\"text\":\" your \"}COLOR splash text!",
        "Also try StarSpeed18!",
        "Alot of cows were harmed for this game",
        "Is this the place to post Ban Appeals?",
        "Can you sign my TARDIS?",
        "1.12.2",
        "Star COLOR{\"color\":[4,144,4,255],\"text\":\"Weed\"}COLOR !",
        "Is this the Dalek Mod?",
        "Theres a bee inside me",
        "Toppings in Burgers are COLOR{\"color\":[144,36,75,255],\"text\":\" MIDDLINGS \"}COLOR !",
        "Blackadder likes men!",
        "Make sure to bully COLOR{\"color\":[144,36,75,255],\"text\":\" Derpy \"}COLOR !",
        "SWD = Special Waffle Dalek!",
        "Jayson broke it",
        "It is not Space Invaders!"
    };


    std::vector<std::string> DM_SPLASHES = {
"100% -Creative (Apparently)",
  "#IDATW",
  "Story Mode is made in Python.",
  "Story Mode?",
  "26 billion% British",
  "Frank!",
  "RedDash is a horse.",
  "The API isn't real",
  "You're on THIN ice!",
  "*HIGHFIVE*",
  "What if you kissed an ugly?",
  "Sonic toasters!?!",
  "I AM YOUNGER!",
  "LONDON 1965!",
  "Sitting on a cornflake.",
  "KeyAdapter is not Evil..",
  "I will put you in an oven!",
  "System.out.println(\"What?... MINECRAFT... With?\")",
  "I blame Sam",
  "I CANT GRADIENT THE SIDE OF MY FACE",
  "Dear Dinnerbone, what the hell did you do!",
  "It's Dalek not Delak.",
  "Dormammu! I've come to bargain",
  "It's Dalek not Darkel.",
  "Bread = Conspiracy theory to sell bread",
  "I'm gonna nick all your stuff!",
  "Remember to use Tamir's TARDIS Taxi Service...",
  "Genetlemen, We have a spy..",
  "Big Nose Man!!!!",
  "My Name, My Name, My Name...",
  "We'll carrrry on",
  "Monkey see, monkey do.",
  "Pop goes the weasel",
  "We dont do dress Daleks!",
  "Not very un not un very totally not un Closed Source?",
  "Didgeridontmen",
  "WHY SAM, WHY!!!!",
  "Did you do all the work?",
  "Only on Vic20",
  "Help me, help you.",
  "I feel like my life ain't mine",
  "If You cant make models, what can you make?",
  "Where we're going, we dont need roads!",
  "~Now where shall we go today!?~",
  "The Megablocks Movie?",
  "No to both of you. No. No. No!",
  "Oh crumbs..",
  "Cant right now i'm busy!",
  "LOAD - SAM - ONEY",
  "Has this, ever happened to you?",
  "0118 999 881 99 9119 725 3",
  "Saym in 40 years",
  "LUDUM DARE!!",
  "are you GiftedX?",
  "Saym saym = new Saym();",
  "705 years in the making!",
  "DEFEAT THE DALEKS WITH A SPOON!!",
  "Yes, 75,000 lines for a feature!",
  "Totally Modloader!",
  "James is Father Ted",
  "Asbo Nan?",
  "Everything's a conspiracy!",
  "Sweeping Feather",
  "Shovel Guy!",
  "Hi Minecraft!",
  "Second Edition, for work-groups!",
  "Comes with IE6!",
  "No PC Should Be Without It!",
  "GIMMIE FIVE!",
  "The SW-DOS 5 upgrade is a Hit!",
  "MS-DOS 5 Upgrade with that?",
  "HOW MUCH, ONLY $99, THAT'S RIGHT ONLY $99!, (except in Nebraska)",
  "Developers Developers Developers",
  "What we're doing here will send a giant ripple through the universe.",
  "Where's the forum post about these splashes?",
  "Voldemort Jr.",
  "FEET2014: NOT ACCEPTABLE",
  "I'M OFFENDED!",
  "can you show us how to fly the tardis pls?",
  "A variety of Doctor Who-related content",
  "4,977, not going up is it!?",
  "ARE YOU HAPPY NOW!. yes",
  "\"LOYAL\" Subscribers!",
  "The Ultimate Doctor Who Experience",
  "Less than 4 years in the making!",
  "BLOCK JSONS = HELL",
  "Don't be silly Jen, The Internet doesn't weigh anything",
  "Hello, I can't call now i'm naked.",
  "The Ice is getting thin",
  "Matt x Cows",
  "Jebus Pizza Crust",
  "MOMMY, I'M LAGGING",
  "IS THIS JAVA?!?!?!",
  "Time for a Livestream",
  "What happened to me!?, WHAT HAPPENED TO YOU!",
  "1% Dutc- I mean German",
  "#VoteUKIK",
  "#SkypeSucksMoveToDiscord",
  "I'd say stop being an idiot but I know what's coming",
  "Big Nose, Big Business",
  "I close my borders for Nigel...",
  "Hey %USERNAME%!",
  "Long Island, Strong Island",
  "John says: Matt is the greatest (Not the cow one)",
  "Darth Wopper",
  "Donald rump",
  "Ikaros, normal humans don't fly",
  "I'll wind you up like a VHS!",
  "Plagerism? Add a hat!",
  "Ed was here",
  "Coat-Tree",
  "We all change... all through our lives...",
  "I like chicken",
  "Dash + Matt's Shoes forever",
  "Matt did a commit",
  "Ask Galax to say DMU",
  "Hey hey john wanna see my TARDIS??",
  "Guitarri",
  "#AddWilfredMott",
  "Second Edition, for work groups!",
  "Opening iron doors since 1.4",
  "Henrik is god",
  "ok gromit lad",
  "COMING!!! Alright, gotta go now",
  "Let's work it to the bone!",
  "E.V.I.L.",
  "The Storm is Here",
  "SWD = Special Waffle Dalek!",
  "8 Years in the making!!"
    };
}